sudo: false
language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1

gemfile:
  - gemfiles/gemfile.rails3
  - gemfiles/gemfile.rails4

jdk:
  - oraclejdk8

notifications:
  irc: "irc.freenode.org#projecthydra"

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
